/**
 * Generate TypeScript modules from the word lists in `data/`.
 *
 *   data/profanity-<lang>.txt + data/exceptions-<lang>.txt  ->  src/data/<lang>.ts
 *   every non-English language                              ->  src/languages.ts
 *
 * The lists are embedded as plain line arrays so they work in Node and in browser
 * bundles alike (no filesystem access at runtime). Run automatically by `pnpm build`,
 * `pnpm test` and `pnpm typecheck`. Only counts are printed — never list content.
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DATA_DIR = join(ROOT, "data");
const OUT_DIR = join(ROOT, "src", "data");

const HEADER = "// AUTO-GENERATED by scripts/build-data.ts from data/ — do not edit.\n";

/** A JS identifier for a language code (`fr-CA-u-sd-caqc` -> `fr_CA_u_sd_caqc`). */
export function identifierFor(code: string): string {
  return code.replace(/[^A-Za-z0-9]/g, "_");
}

function readLines(path: string): string[] {
  return readFileSync(path, "utf8").split(/\r?\n/);
}

function main(): void {
  mkdirSync(OUT_DIR, { recursive: true });
  const files = readdirSync(DATA_DIR);
  const langs = files
    .filter((f) => f.startsWith("profanity-") && f.endsWith(".txt"))
    .map((f) => f.slice("profanity-".length, -".txt".length))
    .sort();

  let totalLines = 0;
  for (const code of langs) {
    const rules = readLines(join(DATA_DIR, `profanity-${code}.txt`));
    const excFile = `exceptions-${code}.txt`;
    const exceptions = files.includes(excFile) ? readLines(join(DATA_DIR, excFile)) : [];
    totalLines += rules.length;
    const body =
      `${HEADER}import type { LanguageData } from "../types.js";\n\n` +
      `const ${identifierFor(code)}: LanguageData = {\n` +
      `  code: ${JSON.stringify(code)},\n` +
      `  rules: ${JSON.stringify(rules)},\n` +
      `  exceptions: ${JSON.stringify(exceptions)},\n` +
      `};\n\nexport default ${identifierFor(code)};\n`;
    writeFileSync(join(OUT_DIR, `${code}.ts`), body, "utf8");
  }

  const others = langs.filter((c) => c !== "en");
  const languages =
    `${HEADER}/**\n * Optional word lists for every bundled non-English language. English ships in the\n` +
    ` * core package. Register what you need (named imports stay tree-shakable):\n *\n` +
    ` *   import { registerLanguage } from "curse-away";\n` +
    ` *   import { es, fr } from "curse-away/languages";\n` +
    ` *   registerLanguage(es, fr);\n *\n` +
    ` * or everything at once: \`registerLanguage(...all)\`.\n */\n\n` +
    `import type { LanguageData } from "./types.js";\n` +
    others.map((c) => `import ${identifierFor(c)} from "./data/${c}.js";`).join("\n") +
    `\n\nexport { ${others.map(identifierFor).join(", ")} };\n\n` +
    `/** Every bundled non-English language. */\n` +
    `export const all: LanguageData[] = [${others.map(identifierFor).join(", ")}];\n`;
  writeFileSync(join(ROOT, "src", "languages.ts"), languages, "utf8");

  console.log(`generated ${langs.length} language module(s), ${totalLines} rule line(s)`);
}

main();
