"""Generate src/combining.ts: the code points Python's ``unicodedata.combining()`` reports as
nonzero — exactly the marks pythanity's normalize.py strips after NFKD. JavaScript has no
combining-class data, and ``\\p{M}`` is broader (it also covers spacing vowel signs etc.),
so curse-away embeds this table for parity.

    python scripts/gen-combining.py   (any Python 3; rerun when Python's Unicode version changes)
"""

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "src" / "combining.ts"


def main():
    ranges = []
    for cp in range(sys.maxunicode + 1):
        if unicodedata.combining(chr(cp)):
            if ranges and ranges[-1][1] == cp - 1:
                ranges[-1][1] = cp
            else:
                ranges.append([cp, cp])
    esc = lambda cp: "\\u{%X}" % cp
    cls = "".join(esc(a) if a == b else f"{esc(a)}-{esc(b)}" for a, b in ranges)
    OUT.write_text(
        f"// AUTO-GENERATED by scripts/gen-combining.py (Unicode {unicodedata.unidata_version}).\n"
        "// Code points with a nonzero canonical combining class: exactly what pythanity's\n"
        "// normalize.py strips after NFKD. Used as a regex character-class body (u flag).\n"
        f'export const COMBINING_CLASS = "{cls}";\n',
        encoding="utf-8",
    )
    print(f"{len(ranges)} ranges, {sum(b - a + 1 for a, b in ranges)} code points, "
          f"Unicode {unicodedata.unidata_version}")


if __name__ == "__main__":
    main()
